linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - ineffassign
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

run:
  timeout: 5m
